version: "3.7"

services:

  proxy:
    image: traefik:v2.9
    restart: on-failure
    command:
      - "--log.level=DEBUG"
      - "--api=true"
      - "--api.dashboard=true"
      - "--api.insecure=true"  # <- DON'T USE THIS LINE IN PRODUCTION
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.frontend.address=:${FRONTEND_PORT}"
      - "--entrypoints.backend.address=:${BACKEND_PORT}"
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
      - "${BACKEND_PORT}:${BACKEND_PORT}"
      - "8080:8080"
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true

  frontend:
    build:
      context: frontend
    restart: on-failure
    environment:
      - VITE_HOST=0.0.0.0
      - VITE_PORT=${FRONTEND_PORT}
      - VITE_API_HOST=localhost:${BACKEND_PORT}
      - VITE_REST_API_PROTOCOL=http://
      - VITE_WS_API_PROTOCOL=ws://
      - VITE_APP_TITLE=Kanban App (dev)
    expose:
      - "${FRONTEND_PORT}"
    volumes:
      - type: bind
        source: ./frontend
        target: /frontend
        read_only: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.entrypoints=frontend"
      - "traefik.http.routers.frontend.rule=Host(`localhost`)"

  backend:
    build:
      context: backend
      target: development
    restart: on-failure
    environment:
      - ENV=development
      - BACKEND_ADDRESS=0.0.0.0:${BACKEND_PORT}
      - DB_CONNECTION_TIMEOUT_MS=10000
      - DB_CONNECTION_URL=mongodb://${DB_USERNAME}:${DB_PASSWORD}@database:${DB_PORT}
      - DB_NAME=kanban
      - PUBSUB_CONNECTION_URL=nats://pubsub:${PUBSUB_PORT}
    expose:
      - "${BACKEND_PORT}"
    volumes:
      - type: bind
        source: ./backend
        target: /backend
        read_only: true
    depends_on:
      - database
      - pubsub
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.entrypoints=backend"
      - "traefik.http.routers.backend.rule=Host(`localhost`)"

  database:
    image: mongo:6
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mongodb_data_container:/data/database

  pubsub:
    image: nats:2
    restart: on-failure

volumes:
  mongodb_data_container: { }
