version: "3.7"

services:

  backend:
    build:
      context: backend
      target: development-watch
    restart: on-failure
    environment:
      - BACKEND_ADDRESS=0.0.0.0:3512
      - DB_CONNECTION_TIMEOUT_MS=10000
      - DB_CONNECTION_URL=mongodb://root:rootpassword@database:27017
      - DB_NAME=kanban
      - PUBSUB_CONNECTION_URL=nats://pubsub:4222
    ports:
      - "3512:3512"
    networks:
      - backend
    volumes:
      - ./backend:/src
    depends_on:
      - database
      - pubsub

  database:
    image: mongo:6
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27018:27017"
    networks:
      - backend
    volumes:
      - mongodb_data_container:/data/database

  pubsub:
    image: nats:2
    restart: on-failure
    ports:
      - "4223:4222"
    networks:
      - backend

volumes:
  mongodb_data_container: {}

networks:
  backend: {}
