version: "3.7"

services:

  proxy:
    image: traefik:v2.9
    restart: on-failure
    command:
      - "--log.level=DEBUG"
      - "--api=true"
      - "--api.dashboard=true"
      - "--api.insecure=true"  # <- DON'T USE THIS LINE IN PRODUCTION
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.frontend.address=:3500"
      - "--entrypoints.backend.address=:3400"
    ports:
      - "3500:3500"
      - "3400:3400"
      - "8080:8080"
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true

  frontend:
    build:
      context: frontend
    restart: on-failure
    environment:
      - VITE_HOST=0.0.0.0
      - VITE_PORT=3500
      - VITE_API_HOST=localhost:3400
      - VITE_REST_API_PROTOCOL=http://
      - VITE_WS_API_PROTOCOL=ws://
      - VITE_APP_TITLE=Kanban App (dev)
    expose:
      - "3500"
    volumes:
      - type: bind
        source: ./frontend
        target: /frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.entrypoints=frontend"
      - "traefik.http.routers.frontend.rule=Host(`localhost`)"

  backend:
    build:
      context: backend
      target: development
    restart: on-failure
    environment:
      - ENV=development
      - BACKEND_ADDRESS=0.0.0.0:3400
      - DB_CONNECTION_TIMEOUT_MS=10000
      - DB_CONNECTION_URL=mongodb://root:rootpassword@database:27017
      - DB_NAME=kanban
      - PUBSUB_CONNECTION_URL=nats://pubsub:4222
    expose:
      - "3400"
    volumes:
      - type: bind
        source: ./backend
        target: /backend
    depends_on:
      - database
      - pubsub
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.entrypoints=backend"
      - "traefik.http.routers.backend.rule=Host(`localhost`)"

  database:
    image: mongo:6
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - mongodb_data_container:/data/database

  pubsub:
    image: nats:2
    restart: on-failure

volumes:
  mongodb_data_container: { }
